<a href="https://colab.research.google.com/github/Huxaifax/DEEP-LEARNING/blob/main/lab_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [3]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [13]:
x_test = x_test/255
x_train = x_train/255

In [14]:
x_train_flatten = x_train.reshape(len(x_train),28*28)
x_test_flatten = x_test.reshape(len(x_test),28*28)

In [15]:
model = keras.Sequential([
                  keras.layers.Dense(10, input_shape = (784,),activation='sigmoid')
])

model.compile(optimizer = 'adam', 
              loss = 'sparse_categorical_crossentropy',
              metrics = ['accuracy']
              ) 
model.fit(x_train_flatten,y_train,epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.4772 - accuracy: 0.8743
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3047 - accuracy: 0.9157
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2833 - accuracy: 0.9211
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2735 - accuracy: 0.9243
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2668 - accuracy: 0.9255


In [16]:
model.evaluate(x_test_flatten,y_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.2744 - accuracy: 0.9237


[0.2744358777999878, 0.9236999750137329]

In [17]:
y_predicted = model.predict(x_test_flatten)
y_predicted[0]

array([2.6818097e-02, 4.3176965e-07, 5.9517741e-02, 9.6398503e-01,
       2.0896494e-03, 1.1277744e-01, 1.0654002e-06, 9.9983132e-01,
       9.0485275e-02, 6.5271688e-01], dtype=float32)

In [18]:
np.argmax(y_predicted[0])

7

In [20]:
y_predicted_labels = [np.argmax(i) for i in y_predicted]

In [22]:
cm = tf.math.confusion_matrix(labels= y_test, predictions= y_predicted_labels)
cm

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 968,    0,    1,    2,    0,    3,    3,    2,    1,    0],
       [   0, 1115,    3,    2,    0,    1,    4,    2,    8,    0],
       [  11,   11,  913,   15,    7,    2,   13,   12,   44,    4],
       [   5,    0,   17,  915,    0,   27,    3,   13,   22,    8],
       [   2,    1,    3,    2,  907,    0,   10,    5,    9,   43],
       [  14,    3,    4,   29,    6,  774,   15,    8,   32,    7],
       [  22,    3,    8,    1,    7,   12,  902,    1,    2,    0],
       [   2,    5,   21,    4,    7,    0,    0,  963,    3,   23],
       [  14,    9,    5,   18,    9,   23,   10,   13,  867,    6],
       [  13,    7,    1,    9,   22,    6,    0,   33,    5,  913]],
      dtype=int32)>

In [24]:
model = keras.Sequential([
                  keras.layers.Dense(100, input_shape = (784,),activation='relu'),
                  keras.layers.Dense(10 ,activation='sigmoid')
])

model.compile(optimizer = 'adam', 
              loss = 'sparse_categorical_crossentropy',
              metrics = ['accuracy']
              ) 
model.fit(x_train_flatten,y_train,epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2722 - accuracy: 0.9216
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1232 - accuracy: 0.9631
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0855 - accuracy: 0.9742
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0660 - accuracy: 0.9798
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0505 - accuracy: 0.9844


In [25]:
model.evaluate(x_test_flatten,y_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.0759 - accuracy: 0.9771


[0.07593975216150284, 0.9771000146865845]